@WebApplication2_HostAddress = http://localhost:5110

GET {{WebApplication2_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{WebApplication2_HostAddress}}/api/user/
Accept: application/json



###

GET {{WebApplication2_HostAddress}}/api/Doctor/
Accept: application/json

###

GET {{WebApplication2_HostAddress}}/api/MedicalRecords/
Accept: application/json
###

GET {{WebApplication2_HostAddress}}/api/Doctor/2
Accept: application/json

###

POST {{WebApplication2_HostAddress}}/api/Doctor/
Content-Type: application/json

{
  "name": "Dr. John Siddique",
  "dateOfBirth": "2000-05-15",
  "contactNumber": "+1-555-1235",
  "speciality": "Cardiology"
}


###

PUT {{WebApplication2_HostAddress}}/api/MedicalRecords/13
Content-Type: application/json

{
  "patient_id": 13
}

